# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4552808805cb2158cb019fefadc1289f60250bed6298eec9ca06218b18f54a6bc0508f859094a76f79eb4bc305d0ef82fc1aa70f1474ef8df5664893d1406a17

test:
  secret_key_base: 8085de5289e0fb94a32fd11939e47980ebecd4d7798b5898d52d1028d84b2067833361a3f93a5bbd7c1f7655ccb72e5bd4cfbce9b40aa2e1a51d4449c10c8fca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
